version: "3.8"
services:
  db:
    image: mysql:8 
    container_name: mysql-container 
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql 
  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/studyTrackerApp 
    ports:
      - 8000:8000
    depends_on:
      - db 
    environment: 
      - DB_NAME=study_tracker
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_HOST=db
      - DB_PORT=3306 
volumes:
  mysql-data:

    
